- name: Memory
  icon: chip
  description: >-
    * minimum 1 GB physical RAM

    * additional memory is needed for your workload

- name: Storage
  icon: hdd
  description: >-
    * minimum 20 GB available disk space

    * recommended: 40GB or more

    * increasing based on the needs of your container workloads
