- name: Memory
  icon: chip
  description: >-
    * minimum 1 GB physical RAM

    * additional memory is needed for your workload, and to use some advanced YaST installation scenarios (eg. Remote Install)

- name: Storage
  icon: hdd
  description: >-
    * / (root) partition: 5 GB available disk space minimum, 20 GB maximum

    * /var partition: 5 GB available disk space minimum, 40 GB or more recommended

    * increasing based on the needs of your container workloads

